"""쿠팡 택배사 코드표 — 정본: 쿠팡 개발자센터 「택배사 코드」(문서 버전 2609170000),
오너가 2026-09-21 텍스트로 붙여넣고 취소선은 같은 날 화면 캡처 4장으로 확정.

규칙(발명 0):
- 코드·이름·자리수·예시는 문서 그대로. 자리수 "-"/빈칸 → lens=None(검증 생략, 화면에 "규격 미지정" 표시).
- active=False = 문서 취소선(합병·폐업) 14건. 검색 결과에 "합병/폐업 — 쿠팡 미지원"으로 회색·선택 불가.
  후계 매핑 금지(KOREX→CJGLS 같은 추정 없음).
- 문서 오기 정정 2건: 코드/이름 열이 뒤바뀐 GKGLOBAL(지케이글로벌)·GONELO(고넬로).
- 중복 1건: GOODSTOLUCK 두 행("-"와 12) → 하나로, 자리수 12.
- "○○와 동일"은 inherit=참조코드 로 자리수 규칙 상속(CVS·BGF→CJGLS, REGISTPOST→EPOST, BANPOOM→HANJIN).
- 영문 포함 형식은 pattern(정규식)으로. 예시에서 도출 가능한 것만(EMS·ARGO·THEBAO·GKGLOBAL·LOGISVALLEY).
  DHL/UPS/TNT/USPS/IPARCEL/ECMS/EFS/SWGEXP는 예시가 혼합이라 alnum=True + 자리수만.
- DIRECT(업체직송): 임의 숫자, 추적 없음 → F44(b)의 "쿠팡 미지원 택배사" 대체 코드.
- 카나리 화이트리스트(현역 확인): CJGLS EPOST HANJIN HYUNDAI KGB.
"""
from __future__ import annotations
from dataclasses import dataclass
from typing import Optional

@dataclass(frozen=True)
class CoupangCourier:
    code: str
    name: str
    lens: Optional[tuple]      # 허용 자리수 튜플, None=미지정
    example: str = ""
    active: bool = True
    alnum: bool = False        # 영문 포함 허용
    pattern: Optional[str] = None
    inherit: Optional[str] = None
    note: str = ""

def R(a, b):  # 범위 "8~16" → (8,…,16)
    return tuple(range(a, b + 1))

CANARY_WHITELIST = ("CJGLS", "EPOST", "HANJIN", "HYUNDAI", "KGB")

COUPANG_COURIERS: tuple[CoupangCourier, ...] = (
    CoupangCourier("HYUNDAI", "롯데택배", (10, 12, 13), "3213084895, 200016500003"),
    CoupangCourier("KGB", "로젠택배", (10, 11), "8073002735, 20286005541"),
    CoupangCourier("EPOST", "우체국", (13,), "6900004147609"),
    CoupangCourier("HANJIN", "한진택배", (10, 12), "1547827315, 300000010634"),
    CoupangCourier("CJGLS", "CJ대한통운", (10, 12), "1234567890, 680405450931"),
    CoupangCourier("KOREX", "대한통운[합병]", (10, 12), "1234567890, 680405450931", active=False),
    CoupangCourier("KDEXP", "경동택배", R(8, 16), "1698100690123456, 12345678"),
    CoupangCourier("DIRECT", "업체직송", None, "202012250930", note="임의의 숫자로만 입력, 배송트래킹 지원안함"),
    CoupangCourier("ILYANG", "일양택배", R(8, 16), "12345678903, 12345678"),
    CoupangCourier("CHUNIL", "천일특송", (11,), "21012345678"),
    CoupangCourier("AJOU", "아주택배", None),
    CoupangCourier("CSLOGIS", "SC로지스", None),
    CoupangCourier("DAESIN", "대신택배", (13,)),
    CoupangCourier("CVS", "CVS택배", (10, 12), "대한통운과 동일", inherit="CJGLS"),
    CoupangCourier("HDEXP", "합동택배", R(8, 16), "1698100690123456, 12345678"),
    CoupangCourier("DHL", "DHL", (10, 13, 20), "6086686653, RX614299816DE, GM565322306000172451, JD014600002115254689", alnum=True),
    CoupangCourier("UPS", "UPS", (18, 9), "1Z602A6E0326718825, 772523220", alnum=True),
    CoupangCourier("FEDEX", "FEDEX", (12, 15), "632431209715, 957465877646062"),
    CoupangCourier("REGISTPOST", "우편등기", (13,), "우체국택배와 동일", inherit="EPOST"),
    CoupangCourier("EMS", "우체국 EMS", (13,), "RA151630799KR", alnum=True, pattern=r"^[A-Z]{2}\d{9}[A-Z]{2}$", note="앞 2자리 영문, 뒤 2자리 영문(국가코드), 나머지 숫자"),
    CoupangCourier("TNT", "TNT", (9, 13), "170171225, GE829867023WW", alnum=True),
    CoupangCourier("USPS", "USPS", (10, 13, 20, 22, 26), "92748999983444513018636497"),
    CoupangCourier("IPARCEL", "i-parcel", (17,), "AEIIND20000448532, 210056227601526US", alnum=True),
    CoupangCourier("GSMNTON", "GSM NtoN", None),
    CoupangCourier("SWGEXP", "성원글로벌", None, "PEDE50012365, PEUS50000001", alnum=True),
    CoupangCourier("PANTOS", "범한판토스", (12,)),
    CoupangCourier("ACIEXPRESS", "ACI Express", (12, 13), "6063424888883"),
    CoupangCourier("DAEWOON", "대운글로벌", None),
    CoupangCourier("AIRBOY", "에어보이익스프레스", None),
    CoupangCourier("KGLNET", "KGL네트웍스", None),
    CoupangCourier("KUNYOUNG", "건영택배", (10,)),
    CoupangCourier("SLX", "SLX택배", (12,), "200016500003"),
    CoupangCourier("HONAM", "우리택배", None),
    CoupangCourier("LINEEXPRESS", "LineExpress", (13,), "6063032562343"),
    CoupangCourier("TWOFASTEXP", "2FastsExpress", (10, 12, 13)),
    CoupangCourier("HPL", "한의사랑택배", (10, 12)),
    CoupangCourier("GOODSTOLUCK", "굿투럭", (12,), note="문서에 두 행(자리수 - / 12) → 12 채택"),
    CoupangCourier("KOREXG", "CJ대한통운특", None),
    CoupangCourier("HANDEX", "한덱스", None),
    CoupangCourier("BGF", "BGF포스트", (10, 12), "대한통운과 동일", inherit="CJGLS"),
    CoupangCourier("ECMS", "ECMS익스프레스", (16,), "ESFSZ11000047679", alnum=True),
    CoupangCourier("WONDERS", "원더스퀵", (15,)),
    CoupangCourier("YONGMA", "용마로지스", None),
    CoupangCourier("SEBANG", "세방택배", (13,)),
    CoupangCourier("NHLOGIS", "농협택배", None),
    CoupangCourier("LOTTEGLOBAL", "롯데글로벌", None),
    CoupangCourier("GSIEXPRESS", "GSI익스프레스", (13,)),
    CoupangCourier("EFS", "EFS", (18,), "802279800499118623"),
    CoupangCourier("DHLGLOBALMAIL", "DHL GlobalMail", None),
    CoupangCourier("HILOGIS", "Hi택배", (12,), active=False),
    CoupangCourier("GPSLOGIX", "GPS로직", None),
    CoupangCourier("CRLX", "시알로지텍", (12, 13)),
    CoupangCourier("BRIDGE", "브리지로지스", None),
    CoupangCourier("HOMEINNOV", "홈이노베이션로지스", (12,)),
    CoupangCourier("CWAY", "씨웨이", (12, 13)),
    CoupangCourier("GNETWORK", "자이언트", (15,)),
    CoupangCourier("ACEEXP", "ACE Express", (13,)),
    CoupangCourier("WEVILL", "우리동네택배", (12,)),
    CoupangCourier("FOREVERPS", "퍼레버택배", (11,)),
    CoupangCourier("WARPEX", "워펙스", (12,)),
    CoupangCourier("QXPRESS", "큐익스프레스", (10, 12)),
    CoupangCourier("SMARTLOGIS", "스마트로지스", (12, 13)),
    CoupangCourier("HOMEPICK", "홈픽택배", (12,)),
    CoupangCourier("GTSLOGIS", "GTS로지스", None),
    CoupangCourier("ESTHER", "에스더쉬핑", None),
    CoupangCourier("INTRAS", "로토스", None),
    CoupangCourier("EUNHA", "은하쉬핑", None),
    CoupangCourier("UFREIGHT", "유프레이트 코리아", None),
    CoupangCourier("LSERVICE", "엘서비스", (11, 12, 13)),
    CoupangCourier("TPMLOGIS", "로지스밸리", None),
    CoupangCourier("ZENIELSYSTEM", "제니엘시스템", (15,)),
    CoupangCourier("ANYTRACK", "애니트랙", None),
    CoupangCourier("JLOGIST", "제이로지스트", (12,)),
    CoupangCourier("CHAINLOGIS", "두발히어로(4시간당일택배)", R(9, 15)),
    CoupangCourier("QRUN", "큐런", (12,)),
    CoupangCourier("FRESHSOLUTIONS", "프레시솔루션", None),
    CoupangCourier("HIVECITY", "하이브시티", (10, 12)),
    CoupangCourier("HANSSEM", "한샘", None),
    CoupangCourier("SFC", "SFC(Santai)", None),
    CoupangCourier("JNET", "J-NET", None),
    CoupangCourier("GENIEGO", "지니고", (12,)),
    CoupangCourier("PANASIA", "판아시아", None),
    CoupangCourier("ELIAN", "elianpost", None),
    CoupangCourier("LOTTECHILSUNG", "롯데칠성", None),
    CoupangCourier("SBGLS", "SBGLS", None),
    CoupangCourier("ALLTAKOREA", "올타코리아", None),
    CoupangCourier("YUNDA", "yunda express", None),
    CoupangCourier("VALEX", "발렉스", None),
    CoupangCourier("KOKUSAI", "국제익스프레스", None),
    CoupangCourier("XINPATEK", "윈핸드해운항공", None),
    CoupangCourier("HEREWEGO", "탱고앤고", None),
    CoupangCourier("WOONGJI", "웅지익스프레스", None),
    CoupangCourier("PINGPONG", "핑퐁", None),
    CoupangCourier("YDH", "YDH", None),
    CoupangCourier("CARGOPLEASE", "화물부탁해", None),
    CoupangCourier("LOGISPOT", "로지스팟", None),
    CoupangCourier("FRESHMATES", "프레시메이트", None),
    CoupangCourier("VROONG", "부릉", None),
    CoupangCourier("NKLS", "NK로지솔루션", None),
    CoupangCourier("DODOFLEX", "도도플렉스", None),
    CoupangCourier("ETOMARS", "이투마스", None),
    CoupangCourier("SHIPNERGY", "배송하기좋은날", None),
    CoupangCourier("VENDORPIA", "벤더피아", None),
    CoupangCourier("COSHIP", "캐나다쉬핑", None),
    CoupangCourier("GDAKOREA", "지디에이코리아", None),
    CoupangCourier("BABABA", "바바바로지스", None),
    CoupangCourier("TEAMFRESH", "팀프레시", None),
    CoupangCourier("HOME1004", "1004홈", None),
    CoupangCourier("NAEUN", "나은물류", None),
    CoupangCourier("ACCCARGO", "acccargo", None),
    CoupangCourier("NTLPS", "엔티엘피스", None),
    CoupangCourier("EKDP", "삼다수가정배송", None),
    CoupangCourier("HOTSINGCARGO", "허싱카고코리아", None),
    CoupangCourier("SINOEX", "SINOTRANS EXPRESS", None),
    CoupangCourier("DRABBIT", "딜리래빗", None),
    CoupangCourier("HOMEPICKTODAY", "홈픽오늘도착", None),
    CoupangCourier("DAERIM", "대림통운", None),
    CoupangCourier("LOGISPARTNER", "로지스파트너", None),
    CoupangCourier("GOBOX", "고박스", None),
    CoupangCourier("FASTBOX", "패스트박스", None),
    CoupangCourier("PANSTAR", "팬스타국제특송", None),
    CoupangCourier("ACTCORE", "에이씨티앤코아물류", None),
    CoupangCourier("KJT", "케이제이티", None),
    CoupangCourier("THEBAO", "더바오", (20,), "B1CA0120220211000001", alnum=True, pattern=r"^B1CA01\d{8}\d{6}$", note="물류센터코드 2자리(고정 B1)+사업부 4자리(고정 CA01)+출고일자 8자리+출고번호 6자리"),
    CoupangCourier("RUSH", "오늘회러쉬", None),
    CoupangCourier("KT", "kt express", None),
    CoupangCourier("IBP", "ibpcorp", None),
    CoupangCourier("HY", "HY", None),
    CoupangCourier("LOGISVALLEY", "로지스밸리", (12,), "숫자 12자리", pattern=r"^\d{12}$"),
    CoupangCourier("TODAY", "투데이", None),
    CoupangCourier("ONEDAYLOGIS", "라스트마일시스템즈", None),
    CoupangCourier("HKHOLDINGS", "에이치케이홀딩스", None),
    CoupangCourier("JIKGUMOON", "직구문", None),
    CoupangCourier("CUBEFLOW", "큐브플로우", None),
    CoupangCourier("SHFLY", "성훈물류", None),
    CoupangCourier("GBS", "지비에스", None),
    CoupangCourier("BANPOOM", "반품구조대", None, "한진택배와 동일", inherit="HANJIN"),
    CoupangCourier("GLOVIS", "현대글로비스", None),
    CoupangCourier("ARGO", "아르고", (16,), "알파벳2자리 + 숫자14자리", alnum=True, pattern=r"^[A-Z]{2}\d{14}$"),
    CoupangCourier("JMNP", "딜리박스", None),
    CoupangCourier("SELC", "삼성로지텍", None),
    CoupangCourier("MTINTER", "엠티인터네셔널", None),
    CoupangCourier("GDSP", "골드스넵스", None),
    CoupangCourier("TODAYPICKUP", "오늘의픽업", None),
    CoupangCourier("YJSGLOBAL", "yjs글로벌", None),
    CoupangCourier("DUXGLOBAL", "유로택배", None),
    CoupangCourier("INTERLOGIS", "인터로지스", None),
    CoupangCourier("WOOJIN", "우진인터로지스", None),
    CoupangCourier("GHSPEED", "지에이치스피드", None),
    CoupangCourier("WIDETECH", "와이드테크", None),
    CoupangCourier("ECOHAI", "에코하이", None),
    CoupangCourier("TONAMI", "토나미", None),
    CoupangCourier("DAIICHI", "제1화물", None),
    CoupangCourier("FUKUYAMA", "후쿠야마통운", None),
    CoupangCourier("KURLYNEXTMILE", "컬리넥스트마일", None),
    CoupangCourier("ARAMEX", "ARAMEX", None),
    CoupangCourier("BISNZ", "BISNZ", None),
    CoupangCourier("INNOS", "이노스", None),
    CoupangCourier("SEORIM", "서림물류", None),
    CoupangCourier("WEMOVE", "위무브", None),
    CoupangCourier("POOLATHOME", "풀앳홈", None),
    CoupangCourier("SPARKLE", "스파클직배송", None),
    CoupangCourier("ICS", "ICS", None),
    CoupangCourier("HANMI", "한미포스트", None),
    CoupangCourier("CAINIAO", "CAINIAO", None),
    CoupangCourier("HWATONG", "화통", None),
    CoupangCourier("ESTLA", "이스트라", None),
    CoupangCourier("IK", "IK물류", None),
    CoupangCourier("PULMUONEWATER", "풀무원샘물", None),
    CoupangCourier("TSG", "티에스지로지스", None),
    CoupangCourier("OCS", "ocs코리아", None),
    CoupangCourier("MDLOGIS", "모든로지스", None),
    CoupangCourier("GCS", "지씨에스", None),
    CoupangCourier("FTF", "물류대장LCS", (12, 13)),
    CoupangCourier("HUBNET", "Hubnet Logistics", None),
    CoupangCourier("WINION_3P", "위니온로지스", None),
    CoupangCourier("WOORIHB", "우리한방택배", None),
    CoupangCourier("LETUS", "레터스", None),
    CoupangCourier("JWTNL", "JWTNL", None),
    CoupangCourier("JCLS", "JCLS", None),
    CoupangCourier("GKGLOBAL", "지케이글로벌", (11,), "24112000002", pattern=r"^\d{11}$", note="문서 열 뒤바뀜 정정(원문: 지케이글로벌 | GKGLOBAL)"),
    CoupangCourier("GONELO", "고넬로", None, note="문서 열 뒤바뀜 정정(원문: 고넬로 | GONELO)"),
    CoupangCourier("CASA", "신세계까사", None),
    CoupangCourier("BRCH", "비알씨에이치", (13,)),
    CoupangCourier("HLDE", "W7", (12,)),
    CoupangCourier("MORNINGGLOBAL", "모닝글로벌", None),
    # ── 이하 취소선(합병·폐업) — 캡처 확정 ──
    CoupangCourier("DNDN", "든든택배", None, active=False),
    CoupangCourier("KGBLS", "KGB로지스", None, active=False),
    CoupangCourier("KGBPS", "KGB택배", None, active=False),
    CoupangCourier("DONGBU", "드림택배", None, active=False),
    CoupangCourier("YELLOW", "옐로우캡", None, active=False),
    CoupangCourier("INNOGIS", "GTX로지스", None, active=False),
    CoupangCourier("DADREAM", "다드림", None, active=False),
    CoupangCourier("IQS", "굿스포스트", None, active=False),
    CoupangCourier("SFEXPRESS", "순풍택배", None, active=False),
    CoupangCourier("LGE", "LG전자", None, active=False),
    CoupangCourier("WINION", "위니온", None, active=False),
    CoupangCourier("WINION2", "위니온(에어컨)", None, active=False),
)

BY_CODE = {c.code: c for c in COUPANG_COURIERS}
INACTIVE = tuple(c.code for c in COUPANG_COURIERS if not c.active)
assert len(INACTIVE) == 14, INACTIVE
assert len(BY_CODE) == len(COUPANG_COURIERS), "코드 중복"
assert all(BY_CODE[c].active for c in CANARY_WHITELIST)
